---
- name: Save ansible base path variable for future use
  set_fact:
    ansible_base_path: "{{ role_path }}/../../"

- name: Create common users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    create_home: yes
    append: yes
    groups: "{{ item.groups }}"
    # password: "{{ item.password | password_hash('sha512') }}"
    password: "{{ item.password }}"
  with_items: "{{ users }}"

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user: 
    name: "{{ item.name }}"
    groups: wheel
    append: yes
    state: "{{  item.state }}"
  with_items: "{{ systemiphus_users }}"
  when: item.sudo

- name: "Set key name based on input"
  set_fact: "{{ item.name }}_key={{ lookup('file', '{{ ansible_base_path }}/{{ item.key_name_location }}') }}"
  with_items: "{{ users }}"
  when: role_as_git_submodule

- name: "Debug the pub key"
  debug:
    msg: "PUB KEY IS: {{ lookup('vars', item.name + '_key') }}"
  with_items: "{{ users }}"
  when: role_as_git_submodule

- name: Add public keys to created users
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state }}"
    key: "{{ item.key }}"
  with_items: "{{ systemiphus_users }}"
  when: not role_as_git_submodule

- name: Add public keys to created users
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state }}"
    key: "{{ lookup('vars', item.name + '_key') }}"
  with_items: "{{ systemiphus_users }}"
  when: role_as_git_submodule

- name: Copy sshd config to host
  copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: "/etc/ssh/sshd_config"
    force: yes
  notify: Restart SSH